#!/usr/bin/env python3
"""CHESS-QC (Quick Compute) launcher.

Choose a front-end, then launch it; each opens a landing page (hub) from which you
navigate to individual applications.

  Desktop : a native PySide6 hub window  ->  click an application -> its calculator.
  Browser : starts a local static server  ->  opens the hub page  -> click -> calculator.
            (The browser version needs a local server: Pyodide fetches the app .py
             over http, which browsers block on file://. This is handled here.)

Usage:
  python run_chess_quick_compute.py                # interactive: pick Desktop/Browser
  python run_chess_quick_compute.py --desktop
  python run_chess_quick_compute.py --web [--port 8000]
  python run_chess_quick_compute.py --desktop --app 2-1   # jump straight to one app
  python run_chess_quick_compute.py --web --app 2-1
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
import time
import webbrowser

ROOT = os.path.dirname(os.path.abspath(__file__))
# repo layout: common/ (shared), frontend/{chessqc_gui,chessqc_web}, backend/applications
for _p in (ROOT, os.path.join(ROOT, "frontend")):   # ROOT -> `common`; frontend -> `chessqc_gui`
    if _p not in sys.path:
        sys.path.insert(0, _p)

# Valid look-and-feel options (shared with chessqc_gui.theme and chessqc_web/theme.js):
#   mode = color (Light/Dark); vibe = shape/typography (Signal/Trail/Forge);
#   badge = class-pill fill (Tinted = pale chip, Solid = full-color chip).
THEME_CHOICES = ["Light", "Dark"]
VIBE_CHOICES = ["Signal", "Trail", "Forge"]
BADGE_CHOICES = ["Tinted", "Solid"]
UNIT_CHOICES = ["SI", "US"]
PALETTE_CHOICES = ["Original", "Vibrant"]
SPEED_CHOICES = ["m/s", "km/h"]   # SI metric display unit for m/s quantities

# ---- USER-EDITABLE DEFAULTS (the splash only asks Desktop vs Browser) -------
# Edit to set the look, or override per run with --decimals / --units / --vibe / --mode / --badge.
# Light/Dark is also switchable at run time on the landing page; units per calculator.
DEFAULT_MODE = "Light"        # Light | Dark
DEFAULT_PALETTE = "Original"  # Original | Vibrant  (one palette used across both modes; web)
DEFAULT_VIBE = "Trail"       # Signal | Trail | Forge
DEFAULT_BADGE = "Solid"      # Solid / Tinted
DEFAULT_UNITS = "SI"         # SI | US  (unit system the calculators open in)
DEFAULT_SPEED_SI = "km/h"    # SI metric unit for m/s quantities: m/s | km/h
DEFAULT_DECIMALS = 2         # 0-8
DEFAULT_TAG = "βeta"         # release tag shown as a superscript on the landing wordmark
                             # (Greek beta + "eta"; e.g. "βeta", "rc", "v1"); set to "" to hide it
DEFAULT_TAG_SIZE = 0.50      # release-tag font size, in em relative to the CHESS-QC wordmark
# -----------------------------------------------------------------------------


def _norm_choice(s: str | None, choices: list) -> str | None:
    """Match a user string to a canonical choice, ignoring case."""
    if not s:
        return None
    key = s.strip().lower()
    for name in choices:
        if key == name.lower():
            return name
    return None


def _norm_vibe(s: str | None) -> str | None:
    return _norm_choice(s, VIBE_CHOICES)


def _norm_badge(s: str | None) -> str | None:
    return _norm_choice(s, BADGE_CHOICES)


def _norm_palette(s: str | None) -> str | None:
    return _norm_choice(s, PALETTE_CHOICES)


def _norm_speed(s: str | None) -> str | None:
    return _norm_choice(s, SPEED_CHOICES)


def _norm_units(s: str | None) -> str | None:
    return _norm_choice(s, UNIT_CHOICES)


def _norm_theme(s: str | None) -> str | None:
    """Match a user-supplied --theme string to a canonical theme name, ignoring case/spaces."""
    if not s:
        return None
    key = s.strip().lower().replace(" ", "")
    for name in THEME_CHOICES:
        if key == name.lower().replace(" ", ""):
            return name
    return None


def _write_web_prefs(decimals: int, theme: str, vibe: str, badge: str, units: str,
                     palette: str, tag: str, tag_size: float, speed_si: str) -> None:
    """Write the launcher-chosen preferences where the static web pages can read them.
    `stamp` changes each launch so a new run resets the landing-page mode toggle to
    this launcher-set default."""
    path = os.path.join(ROOT, "frontend", "chessqc_web", "_prefs.js")
    body = json.dumps({"decimals": int(decimals), "theme": theme, "vibe": vibe,
                       "badge": badge, "units": units, "palette": palette, "tag": tag,
                       "tag_size": float(tag_size), "speed_si": speed_si,
                       "stamp": int(time.time())})
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by run_chess_quick_compute.py, launcher-set preferences. */\n"
                 f"window.CHESSQC_PREFS = {body};\n")

# Chrome is the default browser. Override with env CHESSQC_CHROME, else search these.
_CHROME_CANDIDATES = [
    os.environ.get("CHESSQC_CHROME"),
    shutil.which("chrome"), shutil.which("google-chrome"), shutil.which("chromium"),
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    os.path.expandvars(r"%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe"),
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
]


def open_in_chrome(url: str) -> str:
    """Open url in Chrome if found; else the default browser."""
    for path in _CHROME_CANDIDATES:
        if path and os.path.exists(path):
            subprocess.Popen([path, url])
            return f"Chrome ({path})"
    webbrowser.open(url)
    return "default browser (Chrome not found)"


# ---------------- desktop ----------------
def run_desktop(app_id: str | None, decimals: int | None, theme: str | None,
                vibe: str | None, badge: str | None, units: str | None,
                speed_si: str | None = None) -> int:
    try:
        from chessqc_gui.__main__ import discover, resolve, launch, launch_hub
        from chessqc_gui import settings
    except ImportError as exc:
        print(f"Desktop front-end needs PySide6 (pip install PySide6). [{exc}]")
        return 2
    if decimals is not None:
        settings.set_decimals(decimals)
    if theme is not None:
        settings.set_theme(theme)
    if vibe is not None:
        settings.set_vibe(vibe)
    if badge is not None:
        settings.set_badge(badge)
    if units is not None:
        settings.set_units(units)
    if speed_si is not None:
        settings.set_speed_si(speed_si)
    apps = discover()
    if not apps:
        print("No applications found in applications/.")
        return 1
    if app_id:
        mod = resolve(app_id, apps)
        if mod is None:
            print(f"No application matching '{app_id}'. Available: {', '.join(apps)}")
            return 1
        return launch(mod)
    return launch_hub(apps)                      # landing page


# ---------------- browser (serverless web; local static server) ----------------
def _free_port(preferred: int) -> int:
    for p in (preferred, 0):
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.bind(("127.0.0.1", p))
            port = s.getsockname()[1]
            s.close()
            return port
        except OSError:
            continue
    return preferred


def run_web(app_id: str | None, port: int, decimals: int | None, theme: str | None,
            vibe: str | None, badge: str | None, units: str | None,
            palette: str | None = None, tag: str | None = None,
            speed_si: str | None = None) -> int:
    import functools
    import http.server

    _write_web_prefs(decimals if decimals is not None else DEFAULT_DECIMALS,
                     theme or THEME_CHOICES[0], vibe or VIBE_CHOICES[0],
                     badge or BADGE_CHOICES[0], units or DEFAULT_UNITS,
                     palette or DEFAULT_PALETTE, tag if tag is not None else DEFAULT_TAG,
                     DEFAULT_TAG_SIZE, speed_si or DEFAULT_SPEED_SI)
    port = _free_port(port)

    class _QuietHandler(http.server.SimpleHTTPRequestHandler):
        def log_message(self, *a):    # suppress per-request access logs (GET ... 200/304)
            pass

    handler = functools.partial(_QuietHandler, directory=ROOT)
    httpd = http.server.ThreadingHTTPServer(("127.0.0.1", port), handler)

    page = (f"frontend/chessqc_web/calc.html?app={app_id}" if app_id
            else "frontend/chessqc_web/index.html")
    url = f"http://127.0.0.1:{port}/{page}"
    print(f"CHESS-QC web server: http://127.0.0.1:{port}/  (serving {ROOT})")
    print(f"Opening {url}")
    print("First load fetches Pyodide + numpy from the CDN (~10-30 MB), then cached.")
    print("Press Ctrl+C to stop the server.")
    print(f"  via {open_in_chrome(url)}")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped.")
    finally:
        httpd.server_close()
    return 0


# ---------------- splash (graphical chooser) ----------------
def gui_chooser(theme: str, vibe: str) -> str | None:
    """Splash screen: the *only* choice is Desktop vs Browser. (Decimals, vibe and
    the default mode are configured via the constants at the top of this file or the
    CLI flags.) `theme`/`vibe` are used only to style the splash. Returns
    'desktop' | 'web' | 'quit', or None if PySide6 is unavailable (console fallback)."""
    try:
        from chessqc_gui.qt import QtWidgets, Qt
        from chessqc_gui.theme import load_qss
    except Exception:
        return None

    app = QtWidgets.QApplication.instance() or QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(load_qss(theme, vibe))
    dlg = QtWidgets.QDialog()
    dlg.setWindowTitle("CHESS-QC")
    dlg.setMinimumWidth(420)
    result = {"mode": "quit"}
    v = QtWidgets.QVBoxLayout(dlg)
    v.setSpacing(12)

    title = QtWidgets.QLabel("CHESS — Quick Compute (QC)")
    title.setStyleSheet("font-size:22px; font-weight:800;")
    sub = QtWidgets.QLabel("Coastal Hazards, Engineering, and Structures System (CHESS)")
    sub.setObjectName("fieldLabel")
    v.addWidget(title)
    v.addWidget(sub)
    v.addSpacing(4)
    v.addWidget(QtWidgets.QLabel("Launch as:"))

    row = QtWidgets.QHBoxLayout()
    b_desktop = QtWidgets.QPushButton("🖥  Desktop app")
    b_web = QtWidgets.QPushButton("🌐  Browser app")
    for b in (b_desktop, b_web):
        b.setProperty("accent", "true"); b.setMinimumHeight(56)
        b.setCursor(Qt.CursorShape.PointingHandCursor)
        row.addWidget(b)
    v.addLayout(row)

    def choose(m):
        result["mode"] = m
        dlg.accept()
    b_desktop.clicked.connect(lambda: choose("desktop"))
    b_web.clicked.connect(lambda: choose("web"))

    dlg.exec()      # closing without choosing leaves result['mode'] == 'quit'
    return result["mode"]


def _prompt() -> str:
    print("CHESS-QC (Quick Compute)\n")
    print("  1) Desktop  (native PySide6 window)")
    print("  2) Browser  (serverless web, runs at localhost)")
    while True:
        try:
            choice = input("\nSelect [1/2] (q to quit): ").strip().lower()
        except EOFError:
            return "quit"
        if choice in ("1", "d", "desktop"):
            return "desktop"
        if choice in ("2", "b", "browser", "web"):
            return "web"
        if choice in ("q", "quit", ""):
            return "quit"
        print("  please enter 1 or 2.")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Launch CHESS-QC (Quick Compute).")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--desktop", action="store_true", help="launch the native desktop hub")
    g.add_argument("--web", action="store_true", help="launch the serverless web hub")
    ap.add_argument("--app", metavar="ID", help="open this application directly (e.g. 2-1)")
    ap.add_argument("--port", type=int, default=8000, help="web server port (default 8000)")
    ap.add_argument("--decimals", type=int, metavar="N",
                    help=f"decimal places for results, 0-8 (default {DEFAULT_DECIMALS})")
    ap.add_argument("--theme", "--mode", metavar="NAME", dest="theme",
                    help=f"default color mode: {', '.join(THEME_CHOICES)} (default {THEME_CHOICES[0]})")
    ap.add_argument("--vibe", metavar="NAME",
                    help=f"vibe: {', '.join(VIBE_CHOICES)} (default {VIBE_CHOICES[0]})")
    ap.add_argument("--badge", metavar="NAME",
                    help=f"class badge fill: {', '.join(BADGE_CHOICES)} (default {BADGE_CHOICES[0]})")
    ap.add_argument("--units", metavar="NAME",
                    help=f"unit system: {', '.join(UNIT_CHOICES)} (default {DEFAULT_UNITS})")
    ap.add_argument("--palette", metavar="NAME",
                    help=f"color palette (web): {', '.join(PALETTE_CHOICES)} (default {DEFAULT_PALETTE})")
    ap.add_argument("--tag", metavar="TEXT",
                    help=f"release tag on the landing wordmark (default '{DEFAULT_TAG}'; '' to hide)")
    ap.add_argument("--speed", metavar="UNIT",
                    help=f"SI speed unit for m/s quantities: {', '.join(SPEED_CHOICES)} (default {DEFAULT_SPEED_SI})")
    args = ap.parse_args(argv)

    # Look settings come from CLI flag > the user-editable constants above.
    # (The splash never asks for these, only Desktop vs Browser.)
    decimals = min(max(args.decimals, 0), 8) if args.decimals is not None else DEFAULT_DECIMALS
    theme = _norm_theme(args.theme) or DEFAULT_MODE
    if args.theme and _norm_theme(args.theme) is None:
        print(f"Unknown mode '{args.theme}'; valid: {', '.join(THEME_CHOICES)}.")
        return 2
    vibe = _norm_vibe(args.vibe) or DEFAULT_VIBE
    if args.vibe and _norm_vibe(args.vibe) is None:
        print(f"Unknown vibe '{args.vibe}'; valid: {', '.join(VIBE_CHOICES)}.")
        return 2
    badge = _norm_badge(args.badge) or DEFAULT_BADGE
    if args.badge and _norm_badge(args.badge) is None:
        print(f"Unknown badge '{args.badge}'; valid: {', '.join(BADGE_CHOICES)}.")
        return 2
    units = _norm_units(args.units) or DEFAULT_UNITS
    if args.units and _norm_units(args.units) is None:
        print(f"Unknown units '{args.units}'; valid: {', '.join(UNIT_CHOICES)}.")
        return 2
    palette = _norm_palette(args.palette) or DEFAULT_PALETTE
    if args.palette and _norm_palette(args.palette) is None:
        print(f"Unknown palette '{args.palette}'; valid: {', '.join(PALETTE_CHOICES)}.")
        return 2
    tag = args.tag if args.tag is not None else DEFAULT_TAG   # free text; "" hides it
    speed_si = _norm_speed(args.speed) or DEFAULT_SPEED_SI
    if args.speed and _norm_speed(args.speed) is None:
        print(f"Unknown speed unit '{args.speed}'; valid: {', '.join(SPEED_CHOICES)}.")
        return 2

    if args.desktop or args.web:                 # explicit CLI front-end: no splash
        mode = "desktop" if args.desktop else "web"
    else:
        mode = gui_chooser(theme, vibe)          # splash: only Desktop vs Browser
        if mode is None:                         # PySide6 unavailable -> console
            mode = _prompt()
        if mode == "quit":
            print("bye.")
            return 0

    if mode == "desktop":
        return run_desktop(args.app, decimals, theme, vibe, badge, units, speed_si)
    return run_web(args.app, args.port, decimals, theme, vibe, badge, units, palette, tag, speed_si)


if __name__ == "__main__":
    sys.exit(main())
