/* Generated by run_chess_quick_compute.py, launcher-set preferences. */
window.CHESSQC_PREFS = {"decimals": 2, "theme": "Dark", "vibe": "Trail", "badge": "Solid", "units": "SI", "stamp": 1781655391};
