/* Generated by run_chess_quick_compute.py, launcher-set preferences. */
window.CHESSQC_PREFS = {"decimals": 2, "theme": "Light", "vibe": "Trail", "badge": "Solid", "units": "SI", "palette": "Original", "tag": "\u03b2eta", "tag_size": 0.5, "tcwind_speed": "km/h", "stamp": 1781841250};
