/* Generated by run_chess_quick_compute.py, launcher-set preferences. */
window.CHESSQC_PREFS = {"decimals": 2, "theme": "Dark", "vibe": "Trail", "badge": "Solid", "units": "SI", "palette": "Original", "tag": "\u03b2eta", "tag_size": 0.5, "stamp": 1781712620};
