/* Shared application manifest for the web front-end (hub + driver).
 * Add one entry per implemented chessqc_* application. `src` is relative to the page. */
const CHESSQC_APPS = [
  {
    id: "1-1",
    name: "Windspeed Adjustment and Wave Growth",
    area: "Wave Prediction",
    classification: "exact",
    src: "../../backend/applications/chessqc_1_1_windspeed_wave_growth.py",
  },
  {
    id: "1-2",
    name: "Beta-Rayleigh Distribution",
    area: "Wave Prediction",
    classification: "standard",
    src: "../../backend/applications/chessqc_1_2_beta_rayleigh.py",
  },
  {
    id: "1-3",
    name: "Extremal Significant Wave Height Analysis",
    area: "Wave Prediction",
    classification: "exact",
    src: "../../backend/applications/chessqc_1_3_extremal_hs.py",
  },
  {
    id: "1-4",
    name: "Constituent Tide Record Generation",
    area: "Wave Prediction",
    classification: "exact",
    src: "../../backend/applications/chessqc_1_4_tide_record.py",
  },
  {
    id: "1-5",
    name: "Near-surface Wind Speeds",
    area: "Wave Prediction",
    classification: "provisional",
    src: "../../backend/applications/chessqc_1_5_near_surface_wind.py",
  },
  {
    id: "1-6",
    name: "Holland Hurricane Wind Model",
    area: "Wave Prediction",
    classification: "exact",
    src: "../../backend/applications/chessqc_1_6_holland_hurricane.py",
  },
  {
    id: "2-1",
    name: "Linear Wave Theory",
    area: "Wave Theory",
    classification: "exact",
    src: "../../backend/applications/chessqc_2_1_linear_wave_theory.py",
  },
  {
    id: "2-2",
    name: "Cnoidal Wave Theory",
    area: "Wave Theory",
    classification: "exact",
    src: "../../backend/applications/chessqc_2_2_cnoidal_wave_theory.py",
  },
  {
    id: "2-3",
    name: "Fourier Series Wave Theory",
    area: "Wave Theory",
    classification: "exact",
    src: "../../backend/applications/chessqc_2_3_fenton_fourier.py",
  },
  {
    id: "2-4",
    name: "Wave Parameters",
    area: "Wave Theory",
    classification: "exact",
    src: "../../backend/applications/chessqc_2_4_wave_parameters.py",
  },
  {
    id: "2-5",
    name: "Solitary Wave Theory",
    area: "Wave Theory",
    classification: "exact",
    src: "../../backend/applications/chessqc_2_5_solitary_wave.py",
  },
  {
    id: "3-1",
    name: "Linear Wave Theory with Snell's Law",
    area: "Wave Transformation",
    classification: "exact",
    src: "../../backend/applications/chessqc_3_1_snell.py",
  },
  {
    id: "4-1",
    name: "Breakwater Design (Hudson)",
    area: "Structural Design",
    classification: "exact",
    src: "../../backend/applications/chessqc_4_1_breakwater_hudson.py",
  },
  {
    id: "4-2",
    name: "Toe Protection Design",
    area: "Structural Design",
    classification: "exact",
    src: "../../backend/applications/chessqc_4_2_toe_protection.py",
  },
  {
    id: "4-3",
    name: "Nonbreaking Wave Forces at Vertical Walls",
    area: "Structural Design",
    classification: "exact",
    src: "../../backend/applications/chessqc_4_3_vertical_wall_forces.py",
  },
  {
    id: "3-2",
    name: "Irregular Wave Transformation (Goda's Method)",
    area: "Wave Transformation",
    classification: "provisional",
    src: "../../backend/applications/chessqc_3_2_goda_transformation.py",
  },
  {
    id: "3-3",
    name: "Combined Diffraction and Reflection by a Vertical Wedge",
    area: "Wave Transformation",
    classification: "exact",
    src: "../../backend/applications/chessqc_3_3_wedge_diffraction.py",
  },
  {
    id: "3-4",
    name: "Vertical-Wedge Diffraction/Reflection on a Uniform Grid",
    area: "Wave Transformation",
    classification: "exact",
    src: "../../backend/applications/chessqc_3_4_wedge_grid.py",
  },
  {
    id: "4-4",
    name: "Rubble-Mound Revetment Design",
    area: "Structural Design",
    classification: "exact",
    src: "../../backend/applications/chessqc_4_4_revetment_design.py",
  },
  {
    id: "5-1",
    name: "Irregular Wave Runup on Beaches",
    area: "Wave Runup, Transmission, and Overtopping",
    classification: "exact",
    src: "../../backend/applications/chessqc_5_1_irregular_runup_beaches.py",
  },
  {
    id: "5-2",
    name: "Wave Runup and Overtopping on Impermeable Structures",
    area: "Wave Runup, Transmission, and Overtopping",
    classification: "exact",
    src: "../../backend/applications/chessqc_5_2_runup_overtopping_impermeable.py",
  },
  {
    id: "5-3",
    name: "Wave Transmission on Impermeable Structures",
    area: "Wave Runup, Transmission, and Overtopping",
    classification: "exact",
    src: "../../backend/applications/chessqc_5_3_transmission_impermeable.py",
  },
  {
    id: "5-4",
    name: "Wave Transmission through Permeable Structures",
    area: "Wave Runup, Transmission, and Overtopping",
    classification: "provisional",
    src: "../../backend/applications/chessqc_5_4_transmission_permeable.py",
  },
  {
    id: "5-5",
    name: "Wave Setup",
    area: "Wave Runup, Transmission, and Overtopping",
    classification: "exact",
    src: "../../backend/applications/chessqc_5_5_wave_setup.py",
  },
  {
    id: "6-2",
    name: "Time-Dependent Beach and Dune Erosion",
    area: "Littoral Processes",
    classification: "exact",
    src: "../../backend/applications/chessqc_6_2_dune_erosion.py",
  },
  {
    id: "6-1",
    name: "Longshore Sediment Transport",
    area: "Littoral Processes",
    classification: "exact",
    src: "../../backend/applications/chessqc_6_1_longshore_transport.py",
  },
  {
    id: "6-3",
    name: "Longshore Transport using CEDRS Statistics",
    area: "Littoral Processes",
    classification: "standard",
    src: "../../backend/applications/chessqc_6_3_cedrs_transport.py",
  },
  {
    id: "6-4",
    name: "Beach Nourishment Overfill Ratio and Volume",
    area: "Littoral Processes",
    classification: "exact",
    src: "../../backend/applications/chessqc_6_4_beach_nourishment.py",
  },
  {
    id: "6-5",
    name: "Composite Grain-Size Distribution",
    area: "Littoral Processes",
    classification: "exact",
    src: "../../backend/applications/chessqc_6_5_composite_grain_size.py",
  },
  {
    id: "7-2",
    name: "Wave-Current Interaction in Channels",
    area: "Inlet Processes",
    classification: "exact",
    src: "../../backend/applications/chessqc_7_2_wave_current.py",
  },
  {
    id: "8-1",
    name: "Properties of Rectangular Basins",
    area: "Harbor Design",
    classification: "exact",
    src: "../../backend/applications/chessqc_8_1_rectangular_basins.py",
  },
  {
    id: "8-2",
    name: "Vessel-Generated Waves",
    area: "Harbor Design",
    classification: "exact",
    src: "../../backend/applications/chessqc_8_2_vessel_waves.py",
  },
  {
    id: "8-3",
    name: "Surging of a Moored Vessel",
    area: "Harbor Design",
    classification: "exact",
    src: "../../backend/applications/chessqc_8_3_moored_vessel_surge.py",
  },
  {
    id: "9-1",
    name: "Bathystrophic Storm Surge",
    area: "Storm Surge",
    classification: "provisional",
    src: "../../backend/applications/chessqc_9_1_surge_bathystrophic.py",
  },
  {
    id: "7-1",
    name: "Spatially Integrated Numerical Model for Inlet Hydraulics",
    area: "Inlet Processes",
    classification: "provisional",
    src: "../../backend/applications/chessqc_7_1_inlet_hydraulics.py",
  },
  // Coastal Hazards (area 10)
  {
    id: "10-1",
    name: "Water Level Detrending",
    area: "Coastal Hazards",
    classification: "standard",
    src: "../../backend/applications/chessqc_10_1_water_level_detrending.py",
  },
  {
    id: "10-2",
    name: "Non-Tidal Residual",
    area: "Coastal Hazards",
    classification: "standard",
    src: "../../backend/applications/chessqc_10_2_non_tidal_residual.py",
  },
  {
    id: "10-3",
    name: "Peaks Over Threshold",
    area: "Coastal Hazards",
    classification: "standard",
    src: "../../backend/applications/chessqc_10_3_peaks_over_threshold.py",
  },
  // remaining area-10 apps under construction; shown as non-clickable "coming soon" cards.
  { id: "10-4", name: "Probabilistic Simulation Technique", area: "Coastal Hazards", comingSoon: true },
  { id: "10-5", name: "Joint Probability Method", area: "Coastal Hazards", comingSoon: true },
  {
    id: "M-1",
    name: "Miscellaneous Breaker and Steepness Routines",
    area: "Miscellaneous Routines",
    classification: "standard",
    src: "../../backend/applications/chessqc_m_1_breaker_routines.py",
  },
];

// canonical functional-area display order
const CHESSQC_AREAS = [
  "Wave Prediction", "Wave Theory", "Wave Transformation", "Structural Design",
  "Wave Runup, Transmission, and Overtopping", "Littoral Processes",
  "Inlet Processes", "Harbor Design", "Storm Surge", "Coastal Hazards", "Miscellaneous Routines",
];

if (typeof module !== "undefined") module.exports = { CHESSQC_APPS, CHESSQC_AREAS };
